# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

 name: AKS Cleanup Preview
 trigger: none
 pr: none
 schedules:
   - cron: '0 */12 * * *'
     displayName: Clean up every 12 hours
     branches:
       include:
        - master
     always: 'true'

pool: 
  vmImage: vs2017-win2016

steps:
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      # Write your PowerShell commands  here.
      # Write-Host "Sleeping for 180 secs"
      # Start-Sleep -s 180
