# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

name: Monitor AKS AAT 00 Helm Releases
pr: none
schedules:
- cron: '*/2 * * * Mon-Fri'
  displayName: 'everyday'
  branches:
    include:
      - master
  always: 'true'

pool: 
  vmImage: vs2017-win2016

steps:
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      # Write your PowerShell commands here.
      # Write-Host "Sleeping for 180 secs"
      # Start-Sleep -s 180