# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    include:
      - refs/tags/*

pr:
 autoCancel: true  

pool: 'Default'

resources:
  repositories:
  - repository: sources
    type: github
    name: j-rahul/pipelines-java
    ref: 'refs/heads/master'
    endpoint: gh-source-connection

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      # Write your PowerShell commands here.
      # Write-Host "Sleeping for 180 secs"
      # Start-Sleep -s 180

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'